In [7]:
import matplotlib.pyplot as plt
from ODE_RF2.MCV_ode import *
from ODE_RF2.ODE_Solver import *
from ODE_RF2.ODE_tasks import *
from ODE_RF2.NCV_ode import *
from src.score_funcs import *

In [8]:
# Case
K = 2
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1)
# MCV
inlr = 0.01
instep=1
mCV2 = MetaNeuralCV_ode('ode', MetaNeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6,\
                   tasks=tasks, inner_optim=torch.optim.Adam, inner_lr=inlr, meta_lr=2e-3, K=K, inner_steps=instep,\
                   tasks_per_meta_batch=5,\
                   **score_dict)
mCV2.main_loop(num_iterations=2000)
mCV2.test(100, inner_optim=torch.optim.Adam, inner_steps=instep)
np.mean(np.array(mCV2.log_test[0]['Abserr_CVests'])), np.mean(np.array(mCV2.log_test[0]['Abserr_MC_2m_ests'])), np.mean(np.array(mCV2.log_test[0]['Abserr_MCests']))

10/2000. loss: 27.964061641693114
20/2000. loss: 21.188690662384033
30/2000. loss: 12.677747011184692
40/2000. loss: 12.535665941238403
50/2000. loss: 12.744404196739197
60/2000. loss: 21.768822813034056
70/2000. loss: 15.956471920013428
80/2000. loss: 10.481371402740479
90/2000. loss: 13.0963019490242
100/2000. loss: 13.423962235450745
110/2000. loss: 18.772275340557098
120/2000. loss: 6.970543944835663
130/2000. loss: 21.925162899494172
140/2000. loss: 26.01908077597618
150/2000. loss: 21.545803451538085
160/2000. loss: 11.288484168052673
170/2000. loss: 17.702935111522674
180/2000. loss: 9.004867553710938
190/2000. loss: 19.095006251335143
200/2000. loss: 11.365452361106872
210/2000. loss: 9.856925737857818
220/2000. loss: 12.022565698623657
230/2000. loss: 9.009490966796875
240/2000. loss: 8.31558816432953
250/2000. loss: 6.329714465141296
260/2000. loss: 5.860865497589112
270/2000. loss: 14.462975597381591
280/2000. loss: 8.722365808486938
290/2000. loss: 8.367925333976746
300/200

(0.6281172, 1.639386572688818, 2.1095383)

In [9]:
#NCV
K = 2
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1)
out2 = torch.zeros(100,2)
for i in range(100):
    if i%10 ==0:
        print('{}/{}'.format(i+1,100))
    nCV = NeuralCV_ode('ode', NeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6,\
                   tasks=tasks, optim=torch.optim.Adam, lr=2e-3, K=K,\
                   **score_dict)
    __ = nCV.train_val(num_epochs=20, batch_size=5, verbose=False)
    out2[i,0] = torch.tensor(__[0])
    out2[i,1] = torch.tensor(__[1])

# Mean Absolute error: MC_2m abs err | NCV_abs_err
out2.mean(0)

1/100
11/100
21/100
31/100
41/100
51/100
61/100
71/100
81/100
91/100


tensor([1.9039, 2.5945])

In [10]:
# Case
K = 5
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1) # is good when Oscillatory_Task_Distribution(2, 4.5, 5.5, 0.4, 0.6, 0, 1)
# MCV
inlr = 0.01
instep=1
mCV5 = MetaNeuralCV_ode('ode', MetaNeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6,\
                   tasks=tasks, inner_optim=torch.optim.Adam, inner_lr=inlr, meta_lr=2e-3, K=K, inner_steps=instep,\
                   tasks_per_meta_batch=5,\
                   **score_dict)
mCV5.main_loop(num_iterations=2000)
mCV5.test(100, inner_optim=torch.optim.Adam, inner_steps=instep)
np.mean(np.array(mCV5.log_test[0]['Abserr_CVests'])), np.mean(np.array(mCV5.log_test[0]['Abserr_MC_2m_ests'])), np.mean(np.array(mCV5.log_test[0]['Abserr_MCests']))

10/2000. loss: 6.405482888221741
20/2000. loss: 9.47003014087677
30/2000. loss: 5.125806927680969
40/2000. loss: 4.045700979232788
50/2000. loss: 6.918171024322509
60/2000. loss: 5.7333495140075685
70/2000. loss: 5.931632328033447
80/2000. loss: 7.117025089263916
90/2000. loss: 7.409681487083435
100/2000. loss: 5.002206206321716
110/2000. loss: 3.072193944454193
120/2000. loss: 4.15521365404129
130/2000. loss: 3.8294225215911863
140/2000. loss: 2.6726217389106752
150/2000. loss: 3.3400380849838256
160/2000. loss: 3.219298708438873
170/2000. loss: 3.155245637893677
180/2000. loss: 3.035214531421661
190/2000. loss: 2.9733695864677427
200/2000. loss: 3.6352470397949217
210/2000. loss: 2.7944488525390625
220/2000. loss: 2.4435361504554747
230/2000. loss: 3.386460375785828
240/2000. loss: 3.2463273882865904
250/2000. loss: 2.0984551191329954
260/2000. loss: 2.0766526818275453
270/2000. loss: 2.1459009408950807
280/2000. loss: 2.4143054604530336
290/2000. loss: 2.620494747161865
300/2000. lo

(0.3266676, 1.1745471835136414, 1.8635556)

In [11]:
#NCV
K = 5
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1) # is good when Oscillatory_Task_Distribution(2, 4.5, 5.5, 0.4, 0.6, 0, 1)
out5 = torch.zeros(100,2)
for i in range(100):
    if i%10 ==0:
        print('{}/{}'.format(i+1,100))
    nCV = NeuralCV_ode('ode', NeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6, \
                   tasks=tasks, optim=torch.optim.Adam, lr=2e-3, K=K,\
                   **score_dict)
    __ = nCV.train_val(num_epochs=20, batch_size=5, verbose=False)
    out5[i,0] = torch.tensor(__[0])
    out5[i,1] = torch.tensor(__[1])

# Mean Absolute error: MC_2m abs err | NCV_abs_err
out5.mean(0)

1/100
11/100
21/100
31/100
41/100
51/100
61/100
71/100
81/100
91/100


tensor([1.2412, 1.8477])

In [12]:
# Case
K = 10
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1) # is good when Oscillatory_Task_Distribution(2, 4.5, 5.5, 0.4, 0.6, 0, 1)
# MCV
inlr = 0.01
instep=1
mCV10 = MetaNeuralCV_ode('ode', MetaNeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6,\
                   tasks=tasks, inner_optim=torch.optim.Adam, inner_lr=inlr, meta_lr=2e-3, K=K, inner_steps=instep,\
                   tasks_per_meta_batch=5,\
                   **score_dict)
mCV10.main_loop(num_iterations=2000)
mCV10.test(100, inner_optim=torch.optim.Adam, inner_steps=instep)
np.mean(np.array(mCV10.log_test[0]['Abserr_CVests'])), np.mean(np.array(mCV10.log_test[0]['Abserr_MC_2m_ests'])), np.mean(np.array(mCV10.log_test[0]['Abserr_MCests']))

10/2000. loss: 3.177042245864868
20/2000. loss: 3.082046723365784
30/2000. loss: 3.339434015750885
40/2000. loss: 2.7455761671066283
50/2000. loss: 3.6430867671966554
60/2000. loss: 3.334888231754303
70/2000. loss: 3.0025827407836916
80/2000. loss: 2.427233576774597
90/2000. loss: 1.4846380472183227
100/2000. loss: 1.9288481175899506
110/2000. loss: 1.6043316841125488
120/2000. loss: 1.852189201116562
130/2000. loss: 1.2289263606071472
140/2000. loss: 1.398149985074997
150/2000. loss: 1.4612697243690491
160/2000. loss: 1.318725085258484
170/2000. loss: 1.3912202894687653
180/2000. loss: 1.38212993144989
190/2000. loss: 1.4941279947757722
200/2000. loss: 1.221729612350464
210/2000. loss: 1.1172419786453247
220/2000. loss: 1.1511993765830995
230/2000. loss: 1.2665098786354065
240/2000. loss: 1.0146846234798432
250/2000. loss: 0.970200926065445
260/2000. loss: 1.117679613828659
270/2000. loss: 1.2543274223804475
280/2000. loss: 0.9357702732086182
290/2000. loss: 1.279207068681717
300/2000

(0.13130632, 0.7187614250183105, 1.0869296)

In [13]:
#NCV
K = 10
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1)
out10 = torch.zeros(100,2)
for i in range(100):
    if i%10 ==0:
        print('{}/{}'.format(i+1,100))
    nCV = NeuralCV_ode('ode', NeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6,\
                   tasks=tasks, optim=torch.optim.Adam, lr=2e-3, K=K,\
                   **score_dict)
    __ = nCV.train_val(num_epochs=20, batch_size=5, verbose=False)
    out10[i,0] = torch.tensor(__[0])
    out10[i,1] = torch.tensor(__[1])

# Mean Absolute error: MC_2m abs err | NCV_abs_err
out10.mean(0)

1/100
11/100
21/100
31/100
41/100
51/100
61/100
71/100
81/100
91/100


tensor([0.6819, 1.0566])

In [14]:
# Case
K = 20
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1)
# MCV
inlr = 0.01
instep=1
mCV20 = MetaNeuralCV_ode('ode', MetaNeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6,\
                   tasks=tasks, inner_optim=torch.optim.Adam, inner_lr=inlr, meta_lr=2e-3, K=K, inner_steps=instep,\
                   tasks_per_meta_batch=5,\
                   **score_dict)
mCV20.main_loop(num_iterations=2000)
mCV20.test(100, inner_optim=torch.optim.Adam, inner_steps=instep)
np.mean(np.array(mCV20.log_test[0]['Abserr_CVests'])), np.mean(np.array(mCV20.log_test[0]['Abserr_MC_2m_ests'])), np.mean(np.array(mCV20.log_test[0]['Abserr_MCests']))

10/2000. loss: 2.0309908032417296
20/2000. loss: 1.3955675542354584
30/2000. loss: 1.9864452600479126
40/2000. loss: 1.570352518558502
50/2000. loss: 1.4640998780727386
60/2000. loss: 1.1865670263767243
70/2000. loss: 1.0090335667133332
80/2000. loss: 0.8371401906013489
90/2000. loss: 0.6370036184787751
100/2000. loss: 0.7862550139427185
110/2000. loss: 0.8866901874542237
120/2000. loss: 0.7345927774906158
130/2000. loss: 0.6958224236965179
140/2000. loss: 0.598203843832016
150/2000. loss: 0.6022523581981659
160/2000. loss: 0.584757125377655
170/2000. loss: 0.5543266862630845
180/2000. loss: 0.7098299145698548
190/2000. loss: 0.6004450678825378
200/2000. loss: 0.6592648148536682
210/2000. loss: 0.8441999137401581
220/2000. loss: 0.6182867616415024
230/2000. loss: 0.7203179210424423
240/2000. loss: 0.4911184966564178
250/2000. loss: 0.5411743849515915
260/2000. loss: 0.47035386264324186
270/2000. loss: 0.511503267288208
280/2000. loss: 0.5395145028829574
290/2000. loss: 0.47135973870754

(0.100764856, 0.608354344367981, 0.90853333)

In [15]:
#NCV
K = 20
score_dict  = {'SCORE':multivariate_Normal_score,'mean':torch.zeros(1,1), 'cov':torch.ones(1,1)}
tasks = ODE_Task_Distribution(a_min=0, a_max=1)
out20 = torch.zeros(100,2)
for i in range(100):
    if i%10 ==0:
        print('{}/{}'.format(i+1,100))
    nCV = NeuralCV_ode('ode', NeuralCVModel_ode, D_in=1, h_dims=[80] * 3, init_val=torch.tensor([0.]), weight_decay=5.e-6, \
                   tasks=tasks, optim=torch.optim.Adam, lr=2e-3, K=K,\
                   **score_dict)
    __ = nCV.train_val(num_epochs=20, batch_size=5, verbose=False)
    out20[i,0] = torch.tensor(__[0])
    out20[i,1] = torch.tensor(__[1])

# Mean Absolute error: MC_2m abs err | NCV_abs_err
out20.mean(0)

1/100
11/100
21/100
31/100
41/100
51/100
61/100
71/100
81/100
91/100


tensor([0.6043, 0.8585])

In [16]:
import pandas as pd
no_tasks = 100
set_of_ss = [2,5, 10, 20]
no_ss = len(set_of_ss)

In [17]:

for i in range(no_ss):
    if set_of_ss[i] == 2:
        mCV_log = mCV2
        nCV_log = out2
    elif set_of_ss[i] == 5:
        mCV_log = mCV5
        nCV_log = out5
    elif set_of_ss[i] == 10:
        mCV_log = mCV10
        nCV_log = out10
    elif set_of_ss[i] == 20:
        mCV_log = mCV20
        nCV_log = out20
    cur_MCV_data = list(zip(np.array(mCV_log.log_test[0]['Abserr_CVests']), np.repeat('MCV', no_tasks), np.repeat("N={}".format(set_of_ss[i]*2), no_tasks)))
    cur_MCV_data_df = pd.DataFrame(data=cur_MCV_data, columns=['est_abserr', 'method', 'sample_size'])
    if i == 0:
        MCV_data_df = cur_MCV_data_df
    if i >= 1:
        MCV_data_df = MCV_data_df.append(cur_MCV_data_df)


    # NCV
    cur_NCV_data = list(zip(nCV_log[:,1].numpy(), np.repeat('NCV', no_tasks), np.repeat("N={}".format(set_of_ss[i]*2), no_tasks)))
    cur_NCV_data_df = pd.DataFrame(data= cur_NCV_data, columns=['est_abserr', 'method', 'sample_size'])
    if i == 0:
        NCV_data_df = cur_NCV_data_df
    if i >= 1:
        NCV_data_df= NCV_data_df.append(cur_NCV_data_df)

    # MC
    cur_MC_data =  list(zip(nCV_log[:,0].numpy(), np.repeat('MC', no_tasks), np.repeat("N={}".format(set_of_ss[i]*2), no_tasks)))
    cur_MC_data_df = pd.DataFrame(data=cur_MC_data,columns=['est_abserr', 'method', 'sample_size'])
    if i == 0:
        MC_data_df = cur_MC_data_df
    if i >= 1:
        MC_data_df= MC_data_df.append(cur_MC_data_df)





/var/folders/82/52whq67n6vb7v7yv1nxd7zr40000gq/T/ipykernel_98917/3879380279.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  MCV_data_df = MCV_data_df.append(cur_MCV_data_df)
/var/folders/82/52whq67n6vb7v7yv1nxd7zr40000gq/T/ipykernel_98917/3879380279.py:28: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  NCV_data_df= NCV_data_df.append(cur_NCV_data_df)
/var/folders/82/52whq67n6vb7v7yv1nxd7zr40000gq/T/ipykernel_98917/3879380279.py:36: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  MC_data_df= MC_data_df.append(cur_MC_data_df)
/var/folders/82/52whq67n6vb7v7yv1nxd7zr40000gq/T/ipykernel_98917/3879380279.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.c

In [18]:
# Merge into one giant dataset
my_ODE_DF = MCV_data_df.append([MC_data_df, NCV_data_df])

/var/folders/82/52whq67n6vb7v7yv1nxd7zr40000gq/T/ipykernel_98917/838035116.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  my_ODE_DF = MCV_data_df.append([MC_data_df, NCV_data_df])


In [19]:
my_ODE_DF
# Save data
my_ODE_DF.to_pickle("ODE_DF2.pkl")